// <auto-generated />
using System;
using MT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MT.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020000001_UpdateExistingMinistryUserPhone")]
    partial class UpdateExistingMinistryUserPhone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is auto-generated migration file for updating existing ministry user phone
        }
    }
}